spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clinic_management_db
    username: postgres
    password: sandra
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    #user:
      #name: admin
      #password: password00
      #roles: ADMIN
    filter:
      order: 10

jwt:
  secret-key: 4cfab76ef14937c1c0ea519f8fc057a80fcd04a7430f8e8bcd0a7567c272e007b
  expiration-time: 3600000  # 1 hours (in milliseconds)

# Custom Clinic Management Configurations
clinic:
  appointment:
    max-days-ahead: 30 # Max days to schedule an appointment
  working-hours:
    start: 08:00
    end: 17:00



# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.clinic: DEBUG
  file:
    name: logs/clinic-management.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8081
  servlet:
    context-path: /api-clinic
