spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clinic_management_db
    username: postgres
    password: sandra
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: password00
      roles: ADMIN

# Custom Clinic Management Configurations
clinic:
  appointment:
    max-days-ahead: 30 # Max days to schedule an appointment
  working-hours:
    start: 08:00
    end: 17:00


# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.clinic: DEBUG
  file:
    name: logs/clinic-management.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8081
  servlet:
    context-path: /api-clinic
